config/routes.rb
Rails.application.routes.draw do
  root :to => "visits#index"
  resources :tasks
  resources :visits
  resources :caregivers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :caregiver
  belongs_to :patient

  def display_date
    return "#{self.scheduled_start.strftime("%m/%d/%Y @ %I:%M%p")} - #{self.scheduled_end.strftime("%I:%M%p")}"
  end

  def duration
    return ((self.scheduled_end - self.scheduled_start) / 1.minutes).to_i
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:caregiver_id, :patient_id, :scheduled_start, :scheduled_end, :notes, :actual_start, :actual_end)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit, local: true) do |form| %>
  <% if visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caregiver_id %>
    <%= form.select :caregiver_id, options_for_select(Caregiver.all.map{|c|["#{c.lastname}, #{c.firstname}", c.id]}), :selected => :visit_caregiver_id %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.select :patient_id, options_for_select(Patient.all.map{|p|["#{p.lastname}, #{p.firstname}", p.id]}), :selected => :visit_patient_id %>
  </div>

  <div class="field">
    <%= form.label :scheduled_start %>
    <%= form.datetime_select :scheduled_start, id: :visit_scheduled_start, :ampm => true, :minute_step => 10 %>
  </div>

  <div class="field">
    <%= form.label :scheduled_end %>
    <%= form.datetime_select :scheduled_end, id: :visit_scheduled_end, :ampm => true, :minute_step => 10  %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :visit_notes %>
  </div>
<!--
  <div class="field">
    <%= form.label :actual_start %>
    <%= form.datetime_select :actual_start, id: :visit_actual_start, prompt: true %>
  </div>

  <div class="field">
    <%= form.label :actual_end %>
    <%= form.datetime_select :actual_end, id: :visit_actual_end, prompt: true %>
  </div>
  -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visits</h1>

<!--
<table>
  <thead>
    <tr>
      <th>Caregiver</th>
      <th>Patient</th>
      <th>Visit Time</th>
      <!-<th>Notes</th>->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= link_to("#{visit.caregiver.firstname} #{visit.caregiver.lastname}", caregiver_path(visit.caregiver)) %></td>
        <td><%= link_to("#{visit.patient.firstname} #{visit.patient.lastname}", patient_path(visit.patient)) %></td>
        <td><%= "#{visit.scheduled_start.strftime("%m/%d/%Y @ %I:%M%p")} - #{visit.scheduled_end.strftime("%I:%M%p")}" %></td>
        <!-<td><%= visit.notes %></td>->
        <td><%= link_to 'Details', visit %></td>
        <td><%= link_to 'Modify', edit_visit_path(visit) %></td>
        <td><%= link_to 'Cancel', visit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->


<% @visits.each do |visit| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= visit.caregiver.display_name %> caring for <%= visit.patient.display_name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= visit.display_date %></h6>
        <p class="card-text"><%= simple_format visit.notes %></p>
        <%= link_to 'Details', visit, class: "card-link" %>
        <%= link_to 'Modify', edit_visit_path(visit), class: "card-link" %>
      </div>
    </div>
<% end %>

<br>


<%= link_to 'New Visit', new_visit_path, :class => "btn btn-primary", :style => "color:white" %>

app/views/visits/new.html.erb
<h1>New Visit</h1>

<%= render 'form', visit: @visit %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Upcoming Home Visit</h2>


<p>
  <strong>Scheduled:</strong>
  <%= "#{@visit.scheduled_start.strftime("%m/%d/%Y @ %I:%M%p")} - #{@visit.scheduled_end.strftime("%I:%M%p")}" %> -- <%= ((@visit.scheduled_end - @visit.scheduled_start) / 1.minutes).to_i %> Minutes<br/>
</p>

<p>
  <strong>Caregiver:</strong>
  <%= link_to("#{@visit.caregiver.firstname} #{@visit.caregiver.lastname}", caregiver_path(@visit.caregiver)) %>
</p>

<p>
  <strong>Patient:</strong>
  <%= link_to("#{@visit.patient.firstname} #{@visit.patient.lastname}", patient_path(@visit.patient)) %>
</p>

<p>
  <strong>Notes:</strong>
  <%= simple_format @visit.notes %>
</p>

<button type="button" class="btn btn-warning" onclick="alert('not yet implemented');">On My Way</button>
<button type="button" class="btn btn-primary" onclick="alert('not yet implemented');">Start Visit</button>
<button type="button" class="btn btn-danger" onclick="alert('not yet implemented');">Finish Visit</button> <br/><br/>

<% patient_location = "#{@visit.patient.address1} #{@visit.patient.city}, #{@visit.patient.state} #{@visit.patient.zip}" %>
<% caregiver_location = "#{@visit.caregiver.address1} #{@visit.caregiver.city}, #{@visit.caregiver.state} #{@visit.caregiver.zip}" %>

<div class="google-maps">
  <iframe width="600" height="450" frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/directions?origin=<%= caregiver_location %>&destination=<%= patient_location %>&key=AIzaSyAvZoEbbmyfKTbv6YcEtBghRdSaHBNPznI" allowfullscreen></iframe>
</div>

<address>
  <%= @visit.patient.address1 %><br>
  <%= @visit.patient.city %>, <%= @visit.patient.state %> <%= @visit.patient.zip %><br>
  USA
</address>

<hr/>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>