config/routes.rb
Rails.application.routes.draw do
  root :to => "visits#index"
  resources :tasks
  resources :visits
  resources :caregivers
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  has_many :visits

  def display_name
    return "#{self.firstname} #{self.lastname}"
  end
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_action :set_caregiver, only: [:show, :edit, :update, :destroy]

  # GET /caregivers
  # GET /caregivers.json
  def index
    @caregivers = Caregiver.all
  end

  # GET /caregivers/1
  # GET /caregivers/1.json
  def show
  end

  # GET /caregivers/new
  def new
    @caregiver = Caregiver.new
  end

  # GET /caregivers/1/edit
  def edit
  end

  # POST /caregivers
  # POST /caregivers.json
  def create
    @caregiver = Caregiver.new(caregiver_params)

    respond_to do |format|
      if @caregiver.save
        format.html { redirect_to @caregiver, notice: 'Caregiver was successfully created.' }
        format.json { render :show, status: :created, location: @caregiver }
      else
        format.html { render :new }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caregivers/1
  # PATCH/PUT /caregivers/1.json
  def update
    respond_to do |format|
      if @caregiver.update(caregiver_params)
        format.html { redirect_to @caregiver, notice: 'Caregiver was successfully updated.' }
        format.json { render :show, status: :ok, location: @caregiver }
      else
        format.html { render :edit }
        format.json { render json: @caregiver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caregivers/1
  # DELETE /caregivers/1.json
  def destroy
    @caregiver.destroy
    respond_to do |format|
      format.html { redirect_to caregivers_url, notice: 'Caregiver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caregiver
      @caregiver = Caregiver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caregiver_params
      params.require(:caregiver).permit(:firstname, :lastname, :address1, :address2, :city, :state, :country, :zip, :email, :phone, :drivers_license_number, :drivers_license_state, :is_stna, :stna_license_id, :is_lpn, :lpn_license_id, :is_verified)
    end
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/views/caregivers/_form.html.erb
<%= form_with(model: caregiver, local: true) do |form| %>
  <% if caregiver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caregiver.errors.count, "error") %> prohibited this caregiver from being saved:</h2>

      <ul>
      <% caregiver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, id: :caregiver_firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :caregiver_lastname %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :caregiver_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :caregiver_address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :caregiver_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :caregiver_state %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :caregiver_country %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip, id: :caregiver_zip %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :caregiver_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :caregiver_phone %>
  </div>

  <div class="field">
    <%= form.label :drivers_license_number %>
    <%= form.text_field :drivers_license_number, id: :caregiver_drivers_license_number %>
  </div>

  <div class="field">
    <%= form.label :drivers_license_state %>
    <%= form.text_field :drivers_license_state, id: :caregiver_drivers_license_state %>
  </div>

  <div class="field">
    <%= form.label :is_stna %>
    <%= form.check_box :is_stna, id: :caregiver_is_stna %>
  </div>

  <div class="field">
    <%= form.label :stna_license_id %>
    <%= form.text_field :stna_license_id, id: :caregiver_stna_license_id %>
  </div>

  <div class="field">
    <%= form.label :is_lpn %>
    <%= form.check_box :is_lpn, id: :caregiver_is_lpn %>
  </div>

  <div class="field">
    <%= form.label :lpn_license_id %>
    <%= form.text_field :lpn_license_id, id: :caregiver_lpn_license_id %>
  </div>

  <div class="field">
    <%= form.label :is_verified %>
    <%= form.check_box :is_verified, id: :caregiver_is_verified %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caregivers/edit.html.erb
<h1>Editing Caregiver</h1>

<%= render 'form', caregiver: @caregiver %>

<%= link_to 'Show', @caregiver %> |
<%= link_to 'Back', caregivers_path %>

app/views/caregivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caregivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address1</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Is stna</th>
      <th>Is lpn</th>
      <th>Is verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caregivers.each do |caregiver| %>
      <tr>
        <td><%= "#{caregiver.firstname} #{caregiver.lastname}" %></td>
        <td><%= caregiver.address1 %></td>
        <td><%= caregiver.city %></td>
        <td><%= caregiver.state %></td>
        <td><%= caregiver.zip %></td>
        <td><%= caregiver.email %></td>
        <td><%= caregiver.phone %></td>
        <td><%= caregiver.is_stna %></td>
        <td><%= caregiver.is_lpn %></td>
        <td><%= caregiver.is_verified %></td>
        <td><%= link_to 'Show', caregiver %></td>
        <td><%= link_to 'Edit', edit_caregiver_path(caregiver) %></td>
        <td><%= link_to 'Destroy', caregiver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caregiver', new_caregiver_path %>

app/views/caregivers/new.html.erb
<h1>New Caregiver</h1>

<%= render 'form', caregiver: @caregiver %>

<%= link_to 'Back', caregivers_path %>

app/views/caregivers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Caregiver: <%= @caregiver.display_name %></h2>

<p>
  <strong>Address:</strong>
  <address>
    <%= @caregiver.address1 %><br/>
    <% if @caregiver.address2.present? %>
        <%= @caregiver.address2 %><br/>
    <% end %>
    <%= @caregiver.city %>, <%= @caregiver.state %> <%= @caregiver.zip %>
  </address>

<p>
  <strong>Email:</strong>
  <%= @caregiver.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @caregiver.phone %>
</p>

<p>
  <strong>Drivers license number:</strong>
  <%= @caregiver.drivers_license_number %>
</p>

<p>
  <strong>Drivers license state:</strong>
  <%= @caregiver.drivers_license_state %>
</p>

<h2>Skills:</h2>

<p>
  <strong>Is Nursing Aide?:</strong>
  <%= @caregiver.is_stna %>
</p>

<p>
  <strong>STNA License Number:</strong>
  <%= @caregiver.stna_license_id %>
</p>

<p>
  <strong>Is Nurse:?</strong>
  <%= @caregiver.is_lpn %>
</p>

<p>
  <strong>Nursing License Number:</strong>
  <%= @caregiver.lpn_license_id %>
</p>

<p>
  <strong>Is verified:</strong>
  <%= @caregiver.is_verified %>
</p>

<h2>Upcoming Shifts:</h2>
<% next_visits = @caregiver.visits.sort_by &:scheduled_start %>
<% next_visits.each do |visit| %>
    <div class="card">
      <div class="card-body">
        <b><%= visit.patient.display_name %></b><br/>
        <%= link_to(visit.display_date, visit_path(visit)) %> -- <%= visit.duration %> Minutes<br/>
        In <%= time_ago_in_words(visit.scheduled_start) %>
      </div>
    </div>


<% end %>


<%= link_to 'Edit', edit_caregiver_path(@caregiver) %> |
<%= link_to 'Back', caregivers_path %>